pio: Fix unsound Send clippy warning
rp-rs/rp-hal pull request #197
Opened 2021-11-10 21:18 UTC by chinoto

Clippy complains about the following line being unsound: [rp2040-hal/src/pio.rs:535](https://github.com/rp-rs/rp-hal/blob/f9b3d8341d9e8e83d6be89ae3692f85646bde97a/rp2040-hal/src/pio.rs#L535)

```
this implementation is unsound, as some fields in `StateMachine<SM, State>` are `!Send`
`#[warn(clippy::non_send_fields_in_send_ty)]` on by default
add bounds on type parameter `SM` that satisfy `InstalledProgram<SM::PIO>: Send`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#non_send_fields_in_send_ty
```

The warning can be resolved by making PIOExt, StateMachineIndex, and ValidStateMachine be supertraits of Send. This also makes adding the Send bound redundant in a few places.

2021-11-11 17:28 UTC, chinoto commented
Is there ever a case where these traits should not require being Send? Maybe it made more sense to make the Send requirement only apply to usage with StateMachine.

2021-11-17 18:15 UTC, thejpster commented
Paging @ithinuel

2021-11-17 21:16 UTC, ithinuel requested changes
Thanks @thejpster for paging in. I reproduced the lint with nightly.
Thank you @chinoto for looking into to that.

From the tests I did locally, only the first hunk (adding `Send` as a super trait to `PIOExt`) is needed to resolve this lint. This PR can be simplified.

2021-11-22 04:35 UTC, chinoto commented
If I remove the Send requirement from StateMachineIndex, I get: 
> `SM` cannot be sent between threads safely\nrequired because it appears within the type `(P, SM)`
But you're right about `ValidStateMachine` not needing it. The other changes in this branch are to get rid Send bounds made redundant by making PIOExt require Send.
(The extra pushes were because I realized I should put back the Send bound where ValidStateMachine is used)

2022-01-03 22:39 UTC, thejpster commented
Are we good to go on this one? Any other changes @all?

2022-01-06 07:51 UTC, ithinuel approved these changes

2022-01-06 12:57 UTC, merged