Set up for 0.3.0 release.
rp-rs/rp-hal pull request #243
Opened 2021-12-19 19:22 UTC by thejpster

Somehow we already had a bunch of commits talking about 0.3.0, but it
was never released. Hence why this maybe doesn't change as many version
numbers as you might expect.

2021-12-19 21:26 UTC, 9names requested changes

2021-12-19 21:26 UTC, 9names commented on rp2040-hal/CHANGELOG.md
> +- DMA support
We don't have DMA support yet, probably best to leave that for another release

2021-12-19 21:26 UTC, 9names commented on rp2040-hal/CHANGELOG.md
> +- Embedded HAL 1.0 Alpha support
Each alpha is a breaking release, should specify alpha.6 here so users know which version to expect

2021-12-19 21:26 UTC, 9names commented on rp2040-hal/CHANGELOG.md
Missing:
- RTC
- Timers (unless you group that under RTC
- Spinlocks (unless you group that under multicore)
- USB

And "many bug fixes"!

2021-12-19 21:46 UTC, 9names commented on rp2040-hal/CHANGELOG.md
- hardware divide/modulo

2021-12-20 19:54 UTC, thejpster commented
I think that's all the extra items ticked off the list.

2021-12-20 20:23 UTC, 9names approved these changes

2021-12-20 20:26 UTC, merged