Add Solder Party RP2040 Stamp board
rp-rs/rp-hal pull request #261
Opened 2022-01-09 15:10 UTC by jkristell

Add support for the [RP2040 Stamp board](https://www.solder.party/docs/rp2040-stamp/) by Solder Party.

This board has a single "device" - a neopixel. The example I included for this is copied and updated from the feather board example.

2022-01-09 17:25 UTC, thejpster requested changes
Looks good - just a couple of minor nits.

Have you tested this on a Stamp, or was this done simply by referring to the datasheet?

2022-01-09 17:25 UTC, thejpster commented on boards/solderparty-rp2040-stamp/README.md
> +solderparty-rp2040-stamp = "0.1.0"
This will need to be a git url up until 0.1.0 is published.

2022-01-09 17:25 UTC, thejpster commented on boards/solderparty-rp2040-stamp/README.md
> +an [Solder Party RP2040 Stamp]
/a/ [Solder Party RP2040 Stamp]

2022-01-09 17:25 UTC, thejpster commented on boards/solderparty-rp2040-stamp/examples/solderparty_stamp_neopixel_rainbow.rs
> +        // The onboard NeoPixel is attached to GPIO pin #16 on the Feather RP2040.
Should probably change this comment to whatever the Stamp uses

2022-01-09 17:25 UTC, thejpster commented
Paging @ithinuel who I think had some Solder Party hardware incoming.

2022-01-09 17:26 UTC, thejpster commented on boards/solderparty-rp2040-stamp/Cargo.toml
> +authors = ["Johan Kristell <johan.kristell@gmail.com>"]
Are you OK to change this to "The rp-rs Developers", as per #246?

2022-01-09 21:03 UTC, jkristell commented
Thanks for the review. I updated the branch with your suggestions.

Should have mention that it was tested on a Stamp using the carrier board from Solder Party.

2022-01-10 11:22 UTC, jkristell commented
After thinking some more about this, maybe it makes more sense to support the carrier board?: https://www.solder.party/docs/rp2040-stamp/carrier/

The only difference, as far as I can tell, is the naming of the pins, and maybe some pins missing on the carrier board. 

Alternatively, support both, with this crate, with the help of feature flags and default to the carrier feature on.

What do you think?

2022-01-10 22:18 UTC, ithinuel commented
Actually, without knowing I was about to do something with it some people talked to me about this board how they were excited about the stamp form factor and all the pins it exposed. So I'd say that we should definitely expose the pins for the stamp.

Using a feature to reduce the scope/pin naming to the carrier board works for me too 😃

2022-01-11 20:57 UTC, thejpster approved these changes

2022-01-11 20:57 UTC, thejpster commented
I feel like I need to go and rationalise all these colour wheel examples now to use a common colour wheel crate!

2022-01-11 20:58 UTC, merged