Add a nice wrapper for `get_sys_info`
rp-rs/rp-hal pull request #877
Opened 2024-11-18 05:21 UTC by nahla-nee

Implements a nice safe wrapper for `get_sys_info` as described in #839 .

2024-11-18 17:32 UTC, thejpster requested changes
I'd like to see an example of using this API.

2024-11-18 19:01 UTC, nahla-nee commented
Sure! And I'll go ahead make the suggestions changes too. I'll probably do that by tonight (us time). Do you want the example to be added to the existing rom function example? And if so do you want it to replace the existing one?

2024-11-18 22:12 UTC, thejpster commented
I'm ok with it going into the existing example binary. I'm not sure if we need to leave an example of the old API or if we expect people to only use the new one.

2024-11-19 03:06 UTC, nahla-nee commented on rp235x-hal/src/rom_data.rs
> +mod sys_info_api {
My bad, can't believe I missed that 😅 Fixed.

2024-11-19 03:08 UTC, nahla-nee commented
I also went ahead and added some more documentation. It probably could use more work cause I was in a bit of a rush but it should make things easier to read. I also elaborated on the existing examples since we don't have settle for printing the hex representation of the bytes get_sys_info gives back now.

2024-11-23 17:05 UTC, thejpster commented on rp235x-hal/src/rom_data.rs
> +        const fn buffer_length(&self) -> usize {
Maybe add a note that the sys info flags are a bitmask and can be OR'd together, but we only ever send one flag at a time so we don't need to add the sizes together.

2024-11-23 17:08 UTC, thejpster commented on rp235x-hal-examples/src/bin/rom_funcs.rs
> +    let result = hal::rom_data::sys_info_api::chip_info();
These nested matches can be collapsed.

```rust
let chip_info = match hal::rom_data::sys_info_api::chip_info() {
    Ok(Some(info)) => info,
    Ok(None) => {
        _ = writeln!(uart, "chip_info() not supported");
        return;
    }
    Err(e) => {
        _ = writeln!(uart, "Failed to get chip info : {:?}", e);
        return;
    }
};
```

Are we expecting chips to not support chip info?

2024-11-23 17:09 UTC, thejpster commented on rp235x-hal-examples/src/bin/rom_funcs.rs
> +    let result = match result {
These nested matches can be collapsed.

2024-11-23 17:09 UTC, thejpster commented on rp235x-hal-examples/src/bin/rom_funcs.rs
> +    let result = match result {
These nested matches can be collapsed.

2024-11-23 18:02 UTC, nahla-nee commented
I'll get working on those changes. It just occurred to me that I didn't add an api for `get_sys_info_ns`. Do you want that added as well?

2024-11-23 18:53 UTC, thejpster commented
> I'll get working on those changes. It just occurred to me that I didn't add an api for `get_sys_info_ns`. Do you want that added as well?

I guess it would be good to have that, although I haven't written much NS software for the 2350.

2024-11-23 18:59 UTC, thejpster commented on rp235x-hal/src/rom_data.rs
> +                else if buffer[0] == 0 {
```suggestion
                else if buffer[0] == 0 {
                    // The operation returned successfully but the flag wasn't supported
                    // for one reason or another
```

2024-11-23 18:59 UTC, thejpster commented on rp235x-hal/src/rom_data.rs
> +                else if buffer[0] == 0 {
```suggestion
                } else if buffer[0] == 0 {
```

2024-11-23 19:00 UTC, thejpster approved these changes

2024-11-23 19:00 UTC, thejpster commented
Looks great! Thank you.

2024-11-23 19:03 UTC, thejpster commented
ah, needs a `cargo fmt` please

2024-11-23 19:37 UTC, nahla-nee commented
I went ahead and merged the NS branch into my current branch. Hopefully that's not an issue, I glanced at the notification I got about your message which cut off the part about it not being a blocker. And cargo fmt has been ran 😅 forgot i made changes to the examples folder and only ran it in the hal folder

2024-11-23 20:37 UTC, thejpster commented on rp235x-hal/src/rom_data.rs
> +                else if buffer[0] == 0 {
```suggestion
                } else if buffer[0] == 0 {
                    // The operation returned successfully but the flag wasn't supported
                    // for one reason or another
```

2024-11-23 20:38 UTC, thejpster commented on rp235x-hal/src/rom_data.rs
> +    macro_rules! declare_get_sys_info_ns_function {
This macro is never used?

2024-11-23 21:14 UTC, nahla-nee commented on rp235x-hal/src/rom_data.rs
> +    macro_rules! declare_get_sys_info_ns_function {
should be fixed now

2024-11-25 22:07 UTC, thejpster commented
Before:

```text
get_sys_info(CHIP_INFO/0x0001) -> 4
        Supported Flags: 0x0001
        RP2350 Package ID: 0x00000000
        RP2350 Device ID : 0x2d92c1e1
        RP2350 Wafer ID  : 0xb6d90d05
get_sys_info(CPU_INFO/0x0004) -> 2
        Supported Flags: 0x0004
        CPU Architecture: Arm
get_sys_info(FLASH_DEV_INFO/0x0008) -> 2
        Supported Flags: 0x0008
        CS0 Size: 16M
        CS1 Size: None
get_sys_info(BOOT_RANDOM/0x0010) -> 5
        Supported Flags: 0x0010
        A random number: 0xcfb87af017b6a85f4c1de260cef281e3
```

After:

```text
get_sys_info(CHIP_INFO/0x0001)
        RP2350 Package ID: 0x00000000
        RP2350 Device ID : 0x2d92c1e1
        RP2350 Wafer ID  : 0xb6d90d05
get_sys_info(CPU_INFO/0x0004)
        CPU Architecture: Arm
get_sys_info(FLASH_DEV_INFO/0x0008)
        CS1 GPIO: 0
        D8H Erase Supported: false
        CS0 Size: 16M
        CS1 Size: None
get_sys_info(BOOT_RANDOM/0x0010)
        A random number: 0x6713d047488e82a24dc9660817f0f669
```

Looks great!

2024-11-25 22:08 UTC, merged